spring:
  cloud:
    gateway:
      routes:
        - id: posts-route
          uri: ${POSTS_ROUTE_URI:http://localhost:8081}
          predicates:
            - Path=/posts/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service
        - id: comments-route
          uri: ${COMMENTS_ROUTE_URI:http://localhost:8082}
          predicates:
            - Path=/comments/**
          filters:
            - PrefixPath=/api
            - AddResponseHeader=X-Powered-By, DanSON Gateway Service
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true